"""add announcement status

Revision ID: 9d760891be42
Revises: 
Create Date: 2026-05-12 13:29:59.401602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d760891be42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('status', sa.String(length=30), server_default='active', nullable=False))
    op.create_index(op.f('ix_announcements_status'), 'announcements', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_announcements_status'), table_name='announcements')
    op.drop_column('announcements', 'status')
    # ### end Alembic commands ###
